/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ashraf Hameed
 */
public class Home extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt;
    ResultSet rs;
    PreparedStatement pst;
    String nm = null;
    String subject= null;
    String selectedlesson=null;
    String selectedUserid =null;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        con = mysqlconnect.ConnectDb();
        Populate_Subject();
        Populate_Users();
        SubjectAddFrame.setVisible(false);
        LessonsFrame.setVisible(false);
        AddLessonFrame.setVisible(false);
        LessonsContent.setVisible(false);
        UserManagementFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        LessonsFrame = new javax.swing.JInternalFrame();
        Ls_Label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ls_Table = new javax.swing.JTable();
        Ls_Add_Btn = new javax.swing.JButton();
        Ls_Delete_Btn = new javax.swing.JButton();
        Ls_Enter_Btn = new javax.swing.JButton();
        AddLessonFrame = new javax.swing.JInternalFrame();
        Add_Ls_Label = new javax.swing.JLabel();
        Add_Ls_Submit_Btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Add_Ls_TextArea = new javax.swing.JTextArea();
        Add_ls_content_Label = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Add_ls_content_textArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        LessonsContent = new javax.swing.JInternalFrame();
        lessonContent = new javax.swing.JTextArea();
        Update = new javax.swing.JButton();
        ablessonlabel = new javax.swing.JLabel();
        SubjectFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        abadd = new javax.swing.JButton();
        abdelete = new javax.swing.JButton();
        abenter = new javax.swing.JButton();
        SubjectAddFrame = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddNewSubject = new javax.swing.JTextArea();
        abaddnewsubject = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UserManagementFrame = new javax.swing.JInternalFrame();
        us_mng_label = new javax.swing.JLabel();
        user_textField = new javax.swing.JTextField();
        email_textField = new javax.swing.JTextField();
        password_textField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        add_user_btn = new javax.swing.JButton();
        delete_user_btn = new javax.swing.JButton();
        update_user_btn = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LessonsFrame.setVisible(true);

        Ls_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ls_Label.setText("Lessons");

        Ls_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sl.No.", "Lesson"
            }
        ));
        jScrollPane3.setViewportView(Ls_Table);

        Ls_Add_Btn.setText("Add");
        Ls_Add_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ls_Add_BtnActionPerformed(evt);
            }
        });

        Ls_Delete_Btn.setText("Delete");
        Ls_Delete_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ls_Delete_BtnActionPerformed(evt);
            }
        });

        Ls_Enter_Btn.setText("Enter");
        Ls_Enter_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ls_Enter_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LessonsFrameLayout = new javax.swing.GroupLayout(LessonsFrame.getContentPane());
        LessonsFrame.getContentPane().setLayout(LessonsFrameLayout);
        LessonsFrameLayout.setHorizontalGroup(
            LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsFrameLayout.createSequentialGroup()
                .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LessonsFrameLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LessonsFrameLayout.createSequentialGroup()
                                .addComponent(Ls_Add_Btn)
                                .addGap(36, 36, 36)
                                .addComponent(Ls_Delete_Btn)
                                .addGap(30, 30, 30)
                                .addComponent(Ls_Enter_Btn))))
                    .addGroup(LessonsFrameLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(Ls_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        LessonsFrameLayout.setVerticalGroup(
            LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsFrameLayout.createSequentialGroup()
                .addComponent(Ls_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(LessonsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ls_Add_Btn)
                    .addComponent(Ls_Delete_Btn)
                    .addComponent(Ls_Enter_Btn))
                .addGap(82, 82, 82))
        );

        desktopPane.add(LessonsFrame);
        LessonsFrame.setBounds(0, 0, 497, 402);

        AddLessonFrame.setBackground(new java.awt.Color(204, 204, 204));
        AddLessonFrame.setVisible(true);

        Add_Ls_Label.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Add_Ls_Label.setText("Lesson Name");

        Add_Ls_Submit_Btn.setText("Submit");
        Add_Ls_Submit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Ls_Submit_BtnActionPerformed(evt);
            }
        });

        Add_Ls_TextArea.setColumns(20);
        Add_Ls_TextArea.setRows(5);
        jScrollPane4.setViewportView(Add_Ls_TextArea);

        Add_ls_content_Label.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Add_ls_content_Label.setText("Lesson Content");

        Add_ls_content_textArea.setColumns(20);
        Add_ls_content_textArea.setRows(5);
        jScrollPane5.setViewportView(Add_ls_content_textArea);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Add Lesson");

        javax.swing.GroupLayout AddLessonFrameLayout = new javax.swing.GroupLayout(AddLessonFrame.getContentPane());
        AddLessonFrame.getContentPane().setLayout(AddLessonFrameLayout);
        AddLessonFrameLayout.setHorizontalGroup(
            AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonFrameLayout.createSequentialGroup()
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Add_Ls_Label)
                            .addComponent(Add_ls_content_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(Add_Ls_Submit_Btn))
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel3)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        AddLessonFrameLayout.setVerticalGroup(
            AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLessonFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLessonFrameLayout.createSequentialGroup()
                        .addComponent(Add_Ls_Label)
                        .addGap(33, 33, 33)))
                .addGroup(AddLessonFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLessonFrameLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Add_ls_content_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLessonFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Add_Ls_Submit_Btn)
                .addGap(32, 32, 32))
        );

        desktopPane.add(AddLessonFrame);
        AddLessonFrame.setBounds(0, 0, 607, 360);

        LessonsContent.setVisible(true);

        lessonContent.setColumns(20);
        lessonContent.setRows(5);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        ablessonlabel.setText("jLabel5");

        javax.swing.GroupLayout LessonsContentLayout = new javax.swing.GroupLayout(LessonsContent.getContentPane());
        LessonsContent.getContentPane().setLayout(LessonsContentLayout);
        LessonsContentLayout.setHorizontalGroup(
            LessonsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsContentLayout.createSequentialGroup()
                .addGroup(LessonsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LessonsContentLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(Update))
                    .addGroup(LessonsContentLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lessonContent, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LessonsContentLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(ablessonlabel)))
                .addContainerGap(769, Short.MAX_VALUE))
        );
        LessonsContentLayout.setVerticalGroup(
            LessonsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LessonsContentLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(ablessonlabel)
                .addGap(75, 75, 75)
                .addComponent(lessonContent, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        desktopPane.add(LessonsContent);
        LessonsContent.setBounds(0, 0, 1380, 890);

        SubjectFrame.setVisible(true);

        jLabel1.setText("Subjects");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. no.", "Subject Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        abadd.setText("Add");
        abadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaddActionPerformed(evt);
            }
        });

        abdelete.setText("Delete");
        abdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abdeleteActionPerformed(evt);
            }
        });

        abenter.setText("Enter");
        abenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abenterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubjectFrameLayout = new javax.swing.GroupLayout(SubjectFrame.getContentPane());
        SubjectFrame.getContentPane().setLayout(SubjectFrameLayout);
        SubjectFrameLayout.setHorizontalGroup(
            SubjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectFrameLayout.createSequentialGroup()
                .addGroup(SubjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectFrameLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(abadd)
                        .addGap(145, 145, 145)
                        .addComponent(abdelete)
                        .addGap(138, 138, 138)
                        .addComponent(abenter))
                    .addGroup(SubjectFrameLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubjectFrameLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(731, Short.MAX_VALUE))
        );
        SubjectFrameLayout.setVerticalGroup(
            SubjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectFrameLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGroup(SubjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(305, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SubjectFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(abadd)
                            .addComponent(abdelete)
                            .addComponent(abenter))
                        .addGap(205, 205, 205))))
        );

        desktopPane.add(SubjectFrame);
        SubjectFrame.setBounds(0, 0, 1428, 808);

        SubjectAddFrame.setVisible(true);

        jLabel2.setText("Subject Name");

        AddNewSubject.setColumns(20);
        AddNewSubject.setRows(5);
        jScrollPane2.setViewportView(AddNewSubject);

        abaddnewsubject.setText("Add");
        abaddnewsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaddnewsubjectActionPerformed(evt);
            }
        });

        jLabel4.setText("Add Subject");

        javax.swing.GroupLayout SubjectAddFrameLayout = new javax.swing.GroupLayout(SubjectAddFrame.getContentPane());
        SubjectAddFrame.getContentPane().setLayout(SubjectAddFrameLayout);
        SubjectAddFrameLayout.setHorizontalGroup(
            SubjectAddFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectAddFrameLayout.createSequentialGroup()
                .addGroup(SubjectAddFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectAddFrameLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel2)
                        .addGap(149, 149, 149)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubjectAddFrameLayout.createSequentialGroup()
                        .addGap(682, 682, 682)
                        .addComponent(jLabel4))
                    .addGroup(SubjectAddFrameLayout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(abaddnewsubject)))
                .addContainerGap(850, Short.MAX_VALUE))
        );
        SubjectAddFrameLayout.setVerticalGroup(
            SubjectAddFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectAddFrameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(77, 77, 77)
                .addGroup(SubjectAddFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145)
                .addComponent(abaddnewsubject)
                .addContainerGap(775, Short.MAX_VALUE))
        );

        desktopPane.add(SubjectAddFrame);
        SubjectAddFrame.setBounds(0, 0, 1986, 1163);

        UserManagementFrame.setVisible(true);

        us_mng_label.setText("User Management");

        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User name", "Email Address", "Password"
            }
        ));
        user_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(user_table);

        add_user_btn.setText("Add");
        add_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_btnActionPerformed(evt);
            }
        });

        delete_user_btn.setText("delete");
        delete_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_user_btnActionPerformed(evt);
            }
        });

        update_user_btn.setText("update");
        update_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_user_btnActionPerformed(evt);
            }
        });

        username_label.setText("User Name");

        email_label.setText("Email");

        password_label.setText("Password");

        javax.swing.GroupLayout UserManagementFrameLayout = new javax.swing.GroupLayout(UserManagementFrame.getContentPane());
        UserManagementFrame.getContentPane().setLayout(UserManagementFrameLayout);
        UserManagementFrameLayout.setHorizontalGroup(
            UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(password_label)
                .addGap(29, 29, 29)
                .addComponent(password_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(UserManagementFrameLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(add_user_btn)
                .addGap(102, 102, 102)
                .addComponent(delete_user_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_user_btn)
                .addGap(148, 148, 148))
            .addGroup(UserManagementFrameLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UserManagementFrameLayout.createSequentialGroup()
                        .addComponent(username_label)
                        .addGap(18, 18, 18)
                        .addComponent(user_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(us_mng_label))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        UserManagementFrameLayout.setVerticalGroup(
            UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManagementFrameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(us_mng_label)
                .addGroup(UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserManagementFrameLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_label)
                            .addComponent(email_label)
                            .addComponent(password_label))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UserManagementFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update_user_btn)
                            .addComponent(delete_user_btn)
                            .addComponent(add_user_btn))
                        .addGap(122, 122, 122))))
        );

        desktopPane.add(UserManagementFrame);
        UserManagementFrame.setBounds(0, 0, 710, 489);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Populate_Subject() {
        try {
            pst = con.prepareStatement("select * from subject");
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
        }
    }
    
    private void Populate_Lessons() {
        try {
            pst = con.prepareStatement("select * from lessons where subject_id="+subject);
            rs = pst.executeQuery();
           Ls_Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
        }
    }
    
      private void Populate_Users() {
        try {
            pst = con.prepareStatement("select * from users");
            rs = pst.executeQuery();
            user_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
        }
    }
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void abaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaddActionPerformed
        SubjectFrame.setVisible(false);
        SubjectAddFrame.pack();
        SubjectAddFrame.setVisible(true);
        SubjectAddFrame.requestFocus();
        
    }//GEN-LAST:event_abaddActionPerformed

    private void abdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abdeleteActionPerformed
        int viewIndex = jTable1.getSelectedRow();
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          String selected = model.getValueAt(viewIndex, 0).toString();
    if(viewIndex != -1) {
       
      
        model.removeRow(viewIndex);
         try {                
                    pst = con.prepareStatement("delete from subject where subject_id='"+selected+"' ");
                    pst.executeUpdate();
                }
                catch (Exception w) {
                    JOptionPane.showMessageDialog(this, "Connection Error!");
                } 
        
        SubjectAddFrame.setVisible(false);
    }
    
       
    }//GEN-LAST:event_abdeleteActionPerformed

    private void abaddnewsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaddnewsubjectActionPerformed
        
        String insertsubject = "INSERT INTO Subject( subject) VALUES(?)";
        try {
        pst = con.prepareStatement(insertsubject);
        pst.setString(1, AddNewSubject.getText());
        pst.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        AddNewSubject.setText("");
        Populate_Subject();
        SubjectFrame.setVisible(true);
    }//GEN-LAST:event_abaddnewsubjectActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void abenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abenterActionPerformed
        String lessonsid="";
        String lessonsname="";
        
        try {
            subject=jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString();
            lessonsid="select lesson_id  as Sno,lesson_name as Lessons from lessons where subject_id="+subject;
           
            pst = con.prepareStatement(lessonsid); // create a statement
             
            rs = pst.executeQuery(lessonsid);
           
               Ls_Table.setModel(DbUtils.resultSetToTableModel(rs));
               
             LessonsFrame.setVisible(true);
             SubjectFrame.setVisible(false);
             SubjectAddFrame.setVisible(false);
            
        }
      
            catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_abenterActionPerformed

    private void Ls_Enter_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ls_Enter_BtnActionPerformed
        String lessonscontent="";
        
        try {
            selectedlesson=Ls_Table.getModel().getValueAt(Ls_Table.getSelectedRow(), 0).toString();
            
            lessonscontent="select lesson_name,lesson_content from lessons where lesson_id="+selectedlesson;
           
              pst = con.prepareStatement(lessonscontent); 
             
            rs = pst.executeQuery(lessonscontent);
           
                while (rs.next()) {   
                ablessonlabel.setText(rs.getString(1));
                lessonContent.setText(rs.getString(2)); 
                }
                
             LessonsFrame.setVisible(false);
             LessonsContent.setVisible(true);
              
        }
      
            catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }        
    }//GEN-LAST:event_Ls_Enter_BtnActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

        String updatelessoncontent = "Update lessons set lesson_content=? where lesson_id="+selectedlesson;
        try {
        pst = con.prepareStatement(updatelessoncontent);
        pst.setString(1, lessonContent.getText());
        pst.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LessonsFrame.setVisible(true);
        LessonsContent.setVisible(false);
    }//GEN-LAST:event_UpdateActionPerformed

    private void Ls_Delete_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ls_Delete_BtnActionPerformed
                                                       
        int row = Ls_Table.getSelectedRow();
DefaultTableModel model= (DefaultTableModel)Ls_Table.getModel();

String selected = model.getValueAt(row, 0).toString();

            if (row >= 0) {

                model.removeRow(row);

                try {
                    //Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydatabase", "root", "hey");
                    pst = con.prepareStatement("delete from lessons where lesson_id='"+selected+"' ");
                    pst.executeUpdate();
                }
                catch (Exception w) {
                    JOptionPane.showMessageDialog(this, "Connection Error!");
                }           
            }
    
    }//GEN-LAST:event_Ls_Delete_BtnActionPerformed

    private void Ls_Add_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ls_Add_BtnActionPerformed
                                                  
        LessonsFrame.setVisible(false);
        AddLessonFrame.pack();
        AddLessonFrame.setVisible(true);
        AddLessonFrame.requestFocus();
     
    }//GEN-LAST:event_Ls_Add_BtnActionPerformed

    private void Add_Ls_Submit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Ls_Submit_BtnActionPerformed
     String insertsubject = "INSERT INTO Lessons( lesson_name,lesson_content,subject_id) VALUES(?,?,?)";
        try {
        pst = con.prepareStatement(insertsubject);
        pst.setString(1, Add_Ls_TextArea.getText());
        pst.setString(2,Add_ls_content_textArea.getText());
        pst.setString(3, subject);
        pst.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        Populate_Lessons();
        LessonsFrame.setVisible(true);
        Add_Ls_TextArea.setText("");
        Add_ls_content_textArea.setText("");
        AddLessonFrame.setVisible(false);
        
        
        
    }//GEN-LAST:event_Add_Ls_Submit_BtnActionPerformed

    private void delete_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_user_btnActionPerformed
        int row = user_table.getSelectedRow();
DefaultTableModel model= (DefaultTableModel)user_table.getModel();

String selected = model.getValueAt(row, 0).toString();

            if (row >= 0) {

                model.removeRow(row);

                try {
                    //Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydatabase", "root", "hey");
                    pst = con.prepareStatement("delete from users where user_id='"+selected+"' ");
                    pst.executeUpdate();
                }
                catch (Exception w) {
                    JOptionPane.showMessageDialog(this, "Connection Error!");
                }           
            }
                    user_textField.setText("");
                    email_textField.setText("");
                    password_textField.setText("");
    }//GEN-LAST:event_delete_user_btnActionPerformed

    private void user_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tableMouseClicked
        int row = user_table.getSelectedRow();
DefaultTableModel model= (DefaultTableModel)user_table.getModel();

       selectedUserid = model.getValueAt(row, 0).toString();
String selectedUsername = model.getValueAt(row, 1).toString();
String selectedEmail = model.getValueAt(row, 2).toString();
String selectedPassword = model.getValueAt(row, 3).toString();

            if (row >= 0) {
user_textField.setText(selectedUsername);
email_textField.setText(selectedEmail);
password_textField.setText(selectedPassword);
            
           
            }
    }//GEN-LAST:event_user_tableMouseClicked

    private void add_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_btnActionPerformed
        if(!user_textField.getText().equalsIgnoreCase("") || !email_textField.getText().equalsIgnoreCase("") || !password_textField.getText().equalsIgnoreCase(""))
        {
        String insertuser = "INSERT INTO users( user_name,email_id,user_password) VALUES(?,?,?)";
        try {
        pst = con.prepareStatement(insertuser);
        pst.setString(1, user_textField.getText());
        pst.setString(2, email_textField.getText());
        pst.setString(3, password_textField.getText());
        pst.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter correct user information","Alert",JOptionPane.ERROR_MESSAGE);
        }
        user_textField.setText("");
        email_textField.setText("");
        password_textField.setText("");
        Populate_Users();
      
    }//GEN-LAST:event_add_user_btnActionPerformed

    private void update_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_user_btnActionPerformed
       
                try {
                    pst = con.prepareStatement("Update users set user_name=?,email_id=?,user_password=? where user_id="+selectedUserid);
                     pst.setString(1, user_textField.getText());
                     pst.setString(2, email_textField.getText());
                     pst.setString(3, password_textField.getText());
                    pst.executeUpdate();
                    user_textField.setText("");
                    email_textField.setText("");
                    password_textField.setText("");
                }
                catch (Exception w) {
                    JOptionPane.showMessageDialog(this, "Connection Error!");
                }
                Populate_Users();
    }//GEN-LAST:event_update_user_btnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame AddLessonFrame;
    private javax.swing.JTextArea AddNewSubject;
    private javax.swing.JLabel Add_Ls_Label;
    private javax.swing.JButton Add_Ls_Submit_Btn;
    private javax.swing.JTextArea Add_Ls_TextArea;
    private javax.swing.JLabel Add_ls_content_Label;
    private javax.swing.JTextArea Add_ls_content_textArea;
    private javax.swing.JInternalFrame LessonsContent;
    private javax.swing.JInternalFrame LessonsFrame;
    private javax.swing.JButton Ls_Add_Btn;
    private javax.swing.JButton Ls_Delete_Btn;
    private javax.swing.JButton Ls_Enter_Btn;
    private javax.swing.JLabel Ls_Label;
    private javax.swing.JTable Ls_Table;
    private javax.swing.JInternalFrame SubjectAddFrame;
    private javax.swing.JInternalFrame SubjectFrame;
    private javax.swing.JButton Update;
    private javax.swing.JInternalFrame UserManagementFrame;
    private javax.swing.JButton abadd;
    private javax.swing.JButton abaddnewsubject;
    private javax.swing.JButton abdelete;
    private javax.swing.JButton abenter;
    private javax.swing.JLabel ablessonlabel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton add_user_btn;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JButton delete_user_btn;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_textField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea lessonContent;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField password_textField;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton update_user_btn;
    private javax.swing.JLabel us_mng_label;
    private javax.swing.JTable user_table;
    private javax.swing.JTextField user_textField;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables

}
